# Reads memento-settings.cfg (KVP format written by AMP) and generates
# Settings.override.cs for the Ultima Memento server.
#
# Usage: powershell -File amp-generate-override.ps1 [-CfgPath path] [-OutPath path]

param(
    [string]$CfgPath = "memento-settings.cfg",
    [string]$OutPath = "ultima-memento\World\Info\Scripts\Settings.override.cs"
)

$StringFields = @("S_WebsiteLink", "S_WebsiteName", "S_ServerName")

if (-not (Test-Path $CfgPath)) {
    Write-Host "[AMP] No settings file found at $CfgPath - writing empty override."
    @"
namespace Server
{
	public static class SettingOverrides
	{
		public static void Initialize()
		{
		}
	}
}
"@ | Set-Content -Path $OutPath -Encoding UTF8
    exit 0
}

$lines = @()
$lines += "namespace Server"
$lines += "{"
$lines += "`t/// <summary>"
$lines += "`t/// Auto-generated by AMP - do not edit manually."
$lines += "`t/// Changes made here will be overwritten on next Update."
$lines += "`t/// </summary>"
$lines += "`tpublic static class SettingOverrides"
$lines += "`t{"
$lines += "`t`tpublic static void Initialize()"
$lines += "`t`t{"

foreach ($line in Get-Content $CfgPath) {
    $line = $line.Trim()
    if ([string]::IsNullOrEmpty($line) -or $line.StartsWith("#")) { continue }

    $eqIdx = $line.IndexOf("=")
    if ($eqIdx -lt 0) { continue }

    $key = $line.Substring(0, $eqIdx).Trim()
    $value = $line.Substring($eqIdx + 1)

    if ($key -eq "S_Address") {
        if ([string]::IsNullOrEmpty($value) -or $value -eq "null") {
            $lines += "`t`t`tMySettings.S_Address = null;"
        } else {
            $lines += "`t`t`tMySettings.S_Address = `"$value`";"
        }
    }
    elseif ($key -eq "S_UnidentifiedItem_GuaranteedItemChecks") {
        $lines += "`t`t`tMySettings.S_UnidentifiedItem_GuaranteedItemChecks = new[] { $value };"
    }
    elseif ($StringFields -contains $key) {
        $lines += "`t`t`tMySettings.$key = `"$value`";"
    }
    else {
        $lines += "`t`t`tMySettings.$key = $value;"
    }
}

$lines += "`t`t}"
$lines += "`t}"
$lines += "}"

$lines -join "`r`n" | Set-Content -Path $OutPath -Encoding UTF8
Write-Host "[AMP] Generated $OutPath from $CfgPath"
