#!/bin/bash
# Reads memento-settings.cfg (KVP format written by AMP) and generates
# Settings.override.cs for the Ultima Memento server.
#
# Usage: ./amp-generate-override.sh [cfg_path] [output_path]
#   cfg_path    - defaults to ./memento-settings.cfg
#   output_path - defaults to ./ultima-memento/World/Info/Scripts/Settings.override.cs

set -e

CFG="${1:-memento-settings.cfg}"
OUT="${2:-ultima-memento/World/Info/Scripts/Settings.override.cs}"

if [ ! -f "$CFG" ]; then
    echo "[AMP] No settings file found at $CFG - writing empty override."
    cat > "$OUT" << 'EOF'
namespace Server
{
	public static class SettingOverrides
	{
		public static void Initialize()
		{
		}
	}
}
EOF
    exit 0
fi

# Fields that need C# string quoting (double quotes)
STRING_FIELDS="S_WebsiteLink S_WebsiteName S_ServerName"

# Begin writing the C# file
{
    echo 'namespace Server'
    echo '{'
    echo '	/// <summary>'
    echo '	/// Auto-generated by AMP - do not edit manually.'
    echo '	/// Changes made here will be overwritten on next Update.'
    echo '	/// </summary>'
    echo '	public static class SettingOverrides'
    echo '	{'
    echo '		public static void Initialize()'
    echo '		{'

    while IFS='=' read -r key value; do
        # Skip empty lines
        [ -z "$key" ] && continue
        # Skip comments
        case "$key" in \#*) continue ;; esac
        # Trim whitespace
        key="$(echo "$key" | tr -d '[:space:]')"
        [ -z "$key" ] && continue

        # Handle S_Address specially (can be null)
        if [ "$key" = "S_Address" ]; then
            if [ -z "$value" ] || [ "$value" = "null" ]; then
                echo "			MySettings.S_Address = null;"
            else
                echo "			MySettings.S_Address = \"$value\";"
            fi
        # Handle int array field
        elif [ "$key" = "S_UnidentifiedItem_GuaranteedItemChecks" ]; then
            echo "			MySettings.S_UnidentifiedItem_GuaranteedItemChecks = new[] { $value };"
        # Handle string fields (need C# quoting)
        elif echo " $STRING_FIELDS " | grep -q " $key "; then
            echo "			MySettings.$key = \"$value\";"
        # Everything else: booleans, ints, doubles - output as-is
        else
            echo "			MySettings.$key = $value;"
        fi
    done < "$CFG"

    echo '		}'
    echo '	}'
    echo '}'
} > "$OUT"

echo "[AMP] Generated $OUT from $CFG"
